import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Absolute Return Calculator – Calculate Total Percentage Capital Gain | VolumeCall",
  description:
    "Free Absolute Return Calculator to calculate total percentage profit, point-to-point capital gain, and multiple of money on stocks, mutual funds, and assets.",
  alternates: {
    canonical: "https://volumecall.in/calculators/absolute-return-calculator",
  },
  openGraph: {
    title: "Absolute Return Calculator – Calculate Total Percentage Capital Gain | VolumeCall",
    description:
      "Free Absolute Return Calculator to calculate total percentage profit, point-to-point capital gain, and multiple of money on stocks, mutual funds, and assets.",
    url: "https://volumecall.in/calculators/absolute-return-calculator",
    type: "website",
    siteName: "VolumeCall",
  },
  twitter: {
    card: "summary",
    title: "Absolute Return Calculator – Calculate Total Percentage Capital Gain | VolumeCall",
    description:
      "Free Absolute Return Calculator to calculate total percentage profit, point-to-point capital gain, and multiple of money on stocks, mutual funds, and assets.",
  },
};

const layoutFaqItems = [
  {
    question: "What is Absolute Return?",
    answer:
      "Absolute Return is the total percentage gain or loss generated by an investment over its entire holding period, expressed as a simple percentage of the initial purchase cost, regardless of how long the investment was held.",
  },
  {
    question: "How is Absolute Return calculated?",
    answer:
      "The formula for Absolute Return is: Absolute Return (%) = [ (Current Value - Initial Investment) / Initial Investment ] × 100.",
  },
  {
    question: "When should I use Absolute Return?",
    answer:
      "Absolute Return is ideal for evaluating short-term trades held for less than one year (like swing trading, intraday, or short-term debt) where annualizing returns via CAGR can produce misleadingly high figures.",
  },
  {
    question: "Why is Absolute Return misleading for multi-year investments?",
    answer:
      "A 100% absolute return sounds impressive, but if it took 15 years to achieve, the annualized return is only ~4.7% per year (lagging inflation). Absolute return hides the time dimension.",
  },
  {
    question: "What is the difference between Absolute Return and CAGR?",
    answer:
      "Absolute return measures overall point-to-point percentage growth without factoring in time, while CAGR calculates the standardized annual compound growth rate per year.",
  },
  {
    question: "Can Absolute Return be negative?",
    answer:
      "Yes. If an asset is sold or currently valued below its purchase cost, the absolute return is negative, indicating a capital loss.",
  },
  {
    question: "Does Absolute Return account for dividends or interest received?",
    answer:
      "Standard absolute return calculates price appreciation. To calculate Total Absolute Return, add all dividends, interest, or rental income received to the final value before calculating the percentage.",
  },
  {
    question: "How does inflation impact Absolute Return?",
    answer:
      "Absolute return shows nominal gain. Over multi-year horizons, inflation reduces real purchasing power, meaning a positive nominal absolute return could still result in a real loss.",
  },
  {
    question: "Is Absolute Return the same as Simple Return?",
    answer:
      "Yes, the terms Absolute Return, Total Return, Point-to-Point Return, and Simple Return are often used interchangeably in financial analysis.",
  },
  {
    question: "How are taxes calculated on absolute capital gains in India?",
    answer:
      "Capital gains are categorized as Short-Term Capital Gains (STCG, 20% for listed equity held < 12 months) or Long-Term Capital Gains (LTCG, 12.5% above ₹1.25 Lakh for listed equity held > 12 months).",
  },
];

export default function AbsoluteReturnLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: layoutFaqItems.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  };

  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: "https://volumecall.in",
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Calculators",
        item: "https://volumecall.in/calculators",
      },
      {
        "@type": "ListItem",
        position: 3,
        name: "Absolute Return Calculator",
        item: "https://volumecall.in/calculators/absolute-return-calculator",
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      {children}
    </>
  );
}
