"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import RelatedCalculators from "@/components/calculators/RelatedCalculators";
import { calculateAbsoluteReturn } from "@/lib/financial/returns/absoluteReturn";
import { formatIndianNumber } from "@/lib/stocks/formatting";
import { ArrowUpRight, ChevronDown, ChevronUp, ArrowRight } from "lucide-react";

function numberToWordsIndian(num: number): string {
  if (isNaN(num) || num < 0) return "";
  if (num === 0) return "Zero";
  const units = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"];
  const tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"];

  function convertBelowThousand(n: number): string {
    if (n === 0) return "";
    if (n < 20) return units[n];
    const ten = Math.floor(n / 10);
    const unit = n % 10;
    return tens[ten] + (unit ? " " + units[unit] : "");
  }

  function convertUnderThousandWithHundred(n: number): string {
    const hundred = Math.floor(n / 100);
    const rest = n % 100;
    let str = "";
    if (hundred > 0) str += units[hundred] + " Hundred";
    if (rest > 0) {
      if (str) str += " ";
      str += convertBelowThousand(rest);
    }
    return str;
  }

  let n = Math.floor(num);
  let result = "";
  const crore = Math.floor(n / 10000000);
  n %= 10000000;
  const lakh = Math.floor(n / 100000);
  n %= 100000;
  const thousand = Math.floor(n / 1000);
  const remaining = n % 1000;

  if (crore > 0) result += (crore < 100 ? convertBelowThousand(crore) : convertUnderThousandWithHundred(crore)) + " Crore ";
  if (lakh > 0) result += convertBelowThousand(lakh) + " Lakh ";
  if (thousand > 0) result += convertBelowThousand(thousand) + " Thousand ";
  if (remaining > 0) result += convertUnderThousandWithHundred(remaining);

  return result.trim();
}

const pageFaqItems = [
  {
    question: "What is Absolute Return?",
    answer:
      "Absolute Return is the total percentage gain or loss generated by an investment over its entire holding period, expressed as a simple percentage of the initial purchase cost, regardless of how long the investment was held.",
  },
  {
    question: "How is Absolute Return calculated?",
    answer:
      "The formula for Absolute Return is: Absolute Return (%) = [ (Current Value - Initial Investment) / Initial Investment ] × 100.",
  },
  {
    question: "When should I use Absolute Return?",
    answer:
      "Absolute Return is ideal for evaluating short-term trades held for less than one year (like swing trading, intraday, or short-term debt) where annualizing returns via CAGR can produce misleadingly high figures.",
  },
  {
    question: "Why is Absolute Return misleading for multi-year investments?",
    answer:
      "A 100% absolute return sounds impressive, but if it took 15 years to achieve, the annualized return is only ~4.7% per year (lagging inflation). Absolute return hides the time dimension.",
  },
  {
    question: "What is the difference between Absolute Return and CAGR?",
    answer:
      "Absolute return measures overall point-to-point percentage growth without factoring in time, while CAGR calculates the standardized annual compound growth rate per year.",
  },
  {
    question: "Can Absolute Return be negative?",
    answer:
      "Yes. If an asset is sold or currently valued below its purchase cost, the absolute return is negative, indicating a capital loss.",
  },
  {
    question: "Does Absolute Return account for dividends or interest received?",
    answer:
      "Standard absolute return calculates price appreciation. To calculate Total Absolute Return, add all dividends, interest, or rental income received to the final value before calculating the percentage.",
  },
  {
    question: "How does inflation impact Absolute Return?",
    answer:
      "Absolute return shows nominal gain. Over multi-year horizons, inflation reduces real purchasing power, meaning a positive nominal absolute return could still result in a real loss.",
  },
  {
    question: "Is Absolute Return the same as Simple Return?",
    answer:
      "Yes, the terms Absolute Return, Total Return, Point-to-Point Return, and Simple Return are often used interchangeably in financial analysis.",
  },
  {
    question: "How are taxes calculated on absolute capital gains in India?",
    answer:
      "Capital gains are categorized as Short-Term Capital Gains (STCG, 20% for listed equity held < 12 months) or Long-Term Capital Gains (LTCG, 12.5% above ₹1.25 Lakh for listed equity held > 12 months).",
  },
];

export default function AbsoluteReturnCalculatorPage() {
  const [initialInput, setInitialInput] = useState<string>("50,000");
  const [currentInput, setCurrentInput] = useState<string>("75,000");
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const formatRawDigits = (raw: string) => {
    if (!raw) return "";
    const num = Number(raw);
    return isNaN(num) ? raw : formatIndianNumber(num);
  };

  const parsedInitial = useMemo(() => {
    const raw = initialInput.replace(/,/g, "").trim();
    return !raw || isNaN(Number(raw)) ? 0 : Math.max(0, Number(raw));
  }, [initialInput]);

  const parsedCurrent = useMemo(() => {
    const raw = currentInput.replace(/,/g, "").trim();
    return !raw || isNaN(Number(raw)) ? 0 : Math.max(0, Number(raw));
  }, [currentInput]);

  const initialWords = useMemo(() => numberToWordsIndian(parsedInitial), [parsedInitial]);
  const currentWords = useMemo(() => numberToWordsIndian(parsedCurrent), [parsedCurrent]);

  const result = useMemo(() => {
    return calculateAbsoluteReturn(parsedInitial, parsedCurrent);
  }, [parsedInitial, parsedCurrent]);

  const isGain = result.gain >= 0;

  return (
    <div className="flex flex-col min-h-screen bg-[var(--background)] text-[var(--foreground)]">
      <Header />
      <main className="flex-grow max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
        {/* Breadcrumbs */}
        <div className="text-xs text-[var(--text-secondary)] mb-4 flex items-center space-x-1.5 font-normal">
          <Link href="/" className="hover:text-[var(--foreground)] transition-colors">Home</Link>
          <span>/</span>
          <Link href="/calculators" className="text-[var(--text-muted)] hover:text-[var(--foreground)] transition-colors">Calculators</Link>
          <span>/</span>
          <span className="text-[var(--foreground)] font-medium">Absolute Return Calculator</span>
        </div>

        {/* Header */}
        <div className="mb-8 max-w-3xl">
          <div className="flex items-center space-x-2 text-teal-700 dark:text-teal-400 font-bold text-xs uppercase tracking-wider mb-2">
            <ArrowUpRight className="h-4 w-4" />
            <span>Point-to-Point Capital Gain</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-neutral-950 dark:text-neutral-50">
            Absolute Return Calculator
          </h1>
          <p className="text-xs sm:text-sm text-[var(--text-secondary)] mt-2 leading-relaxed">
            Calculate the total percentage profit, absolute rupee gain, and multiple of money for stocks, mutual funds, gold, and crypto assets.
          </p>
        </div>

        {/* Top Calculator Section */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-stretch mb-12">
          {/* Form Controls */}
          <div className="md:col-span-7 h-full bg-white dark:bg-[#0a0a0a] border border-[var(--border)] rounded-2xl p-6 sm:p-8 space-y-6 shadow-xs">
            {/* Input 1: Initial Investment */}
            <div className="space-y-3">
              <div className="flex justify-between items-start">
                <div>
                  <label htmlFor="abs-initial" className="text-xs font-bold text-neutral-800 dark:text-neutral-200 uppercase tracking-wider block">
                    Initial Investment Amount
                  </label>
                  <span className="text-[11px] text-[var(--text-muted)]">Starting capital / total purchase cost</span>
                </div>
                <div className="flex flex-col items-end space-y-1">
                  <div className="relative flex items-center">
                    <span className="absolute left-2.5 text-xs text-[var(--text-secondary)] font-medium">₹</span>
                    <input
                      id="abs-initial"
                      type="text"
                      inputMode="numeric"
                      autoComplete="off"
                      value={initialInput}
                      onChange={(e) => {
                        const clean = e.target.value.replace(/[^0-9]/g, "").replace(/^0+(?=\d)/, "");
                        setInitialInput(clean === "" ? "" : formatRawDigits(clean));
                      }}
                      className="w-40 sm:w-48 pl-6 pr-2.5 py-1.5 border border-[var(--border)] bg-neutral-50/50 dark:bg-[#121212]/50 text-right text-sm sm:text-base font-bold rounded-lg focus:outline-none focus:ring-1.5 focus:ring-teal-650 transition-all tabular-nums"
                    />
                  </div>
                  {initialWords && <div className="text-xs font-semibold text-teal-700 dark:text-teal-400 text-right">{initialWords}</div>}
                </div>
              </div>
              <input
                type="range"
                min="0"
                max="5000000"
                step="5000"
                autoComplete="off"
                value={Math.min(5000000, Math.max(0, parsedInitial))}
                onChange={(e) => setInitialInput(formatIndianNumber(Number(e.target.value)))}
                className="w-full h-1.5 bg-neutral-200 dark:bg-neutral-800 rounded-lg appearance-none cursor-pointer accent-teal-700 dark:accent-teal-400"
              />
            </div>

            {/* Input 2: Current / Final Value */}
            <div className="space-y-3">
              <div className="flex justify-between items-start">
                <div>
                  <label htmlFor="abs-current" className="text-xs font-bold text-neutral-800 dark:text-neutral-200 uppercase tracking-wider block">
                    Current / Final Investment Value
                  </label>
                  <span className="text-[11px] text-[var(--text-muted)]">Current market value / sale proceeds</span>
                </div>
                <div className="flex flex-col items-end space-y-1">
                  <div className="relative flex items-center">
                    <span className="absolute left-2.5 text-xs text-[var(--text-secondary)] font-medium">₹</span>
                    <input
                      id="abs-current"
                      type="text"
                      inputMode="numeric"
                      autoComplete="off"
                      value={currentInput}
                      onChange={(e) => {
                        const clean = e.target.value.replace(/[^0-9]/g, "").replace(/^0+(?=\d)/, "");
                        setCurrentInput(clean === "" ? "" : formatRawDigits(clean));
                      }}
                      className="w-40 sm:w-48 pl-6 pr-2.5 py-1.5 border border-[var(--border)] bg-neutral-50/50 dark:bg-[#121212]/50 text-right text-sm sm:text-base font-bold rounded-lg focus:outline-none focus:ring-1.5 focus:ring-teal-650 transition-all tabular-nums"
                    />
                  </div>
                  {currentWords && <div className="text-xs font-semibold text-teal-700 dark:text-teal-400 text-right">{currentWords}</div>}
                </div>
              </div>
              <input
                type="range"
                min="0"
                max="10000000"
                step="5000"
                autoComplete="off"
                value={Math.min(10000000, Math.max(0, parsedCurrent))}
                onChange={(e) => setCurrentInput(formatIndianNumber(Number(e.target.value)))}
                className="w-full h-1.5 bg-neutral-200 dark:bg-neutral-800 rounded-lg appearance-none cursor-pointer accent-teal-700 dark:accent-teal-400"
              />
            </div>
          </div>

          {/* Primary Output Card */}
          <div className="md:col-span-5 h-full bg-neutral-50 dark:bg-[#121212]/60 border border-[var(--border)] rounded-2xl p-6 sm:p-8 flex flex-col justify-between space-y-6 shadow-xs min-h-[380px]">
            <div>
              <span className="text-[10px] text-[var(--text-secondary)] font-medium uppercase tracking-wider block">Absolute Percentage Return</span>
              <span className={`text-3xl sm:text-4xl font-black tabular-nums block mt-1 ${isGain ? "text-teal-700 dark:text-teal-400" : "text-rose-600 dark:text-rose-400"}`}>
                {isGain ? "+" : ""}{result.returnPercentage.toFixed(2)}%
              </span>
            </div>

            <div className="space-y-4 pt-4 border-t border-[var(--border)] text-xs">
              <div className="flex justify-between">
                <span className="text-[var(--text-secondary)] font-medium">Net Profit / Loss</span>
                <span className={`font-bold tabular-nums ${isGain ? "text-teal-700 dark:text-teal-400" : "text-rose-600 dark:text-rose-400"}`}>
                  {isGain ? "+" : ""}₹{formatIndianNumber(Math.round(result.gain))}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-[var(--text-secondary)] font-medium">Investment Multiple</span>
                <span className="font-bold tabular-nums">{(parsedInitial > 0 ? parsedCurrent / parsedInitial : 0).toFixed(2)}x</span>
              </div>
            </div>

            <Link
              href="/calculators/cagr-calculator"
              className="inline-flex items-center justify-between px-4 py-2.5 bg-white dark:bg-[#1a1a1a] border border-[var(--border)] rounded-xl text-xs font-bold text-teal-700 dark:text-teal-400 hover:bg-neutral-50 transition-colors"
            >
              <span>Held longer than 1 year? Calculate Annualized CAGR</span>
              <ArrowRight className="h-3.5 w-3.5 ml-2" />
            </Link>
          </div>
        </div>

        {/* Comprehensive Educational Content & FAQs Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-10 border-t border-[var(--border)] pt-10 mb-12 items-start">
          {/* Left Column: Educational Content & FAQs */}
          <div className="lg:col-span-8 space-y-10">
            <section>
              <h2 className="text-xl font-bold text-neutral-950 dark:text-neutral-50 mb-3">What Is Absolute Return?</h2>
              <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
                <strong>Absolute Return</strong> (also known as total return or point-to-point return) measures the overall percentage appreciation or depreciation of an investment from its initial purchase date to its current valuation or final sale date, without adjusting for the time duration taken.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-neutral-950 dark:text-neutral-50 mb-3">How Is Absolute Return Calculated?</h2>
              <div className="p-4 bg-neutral-50 dark:bg-[#121212] border border-[var(--border)] rounded-xl font-mono text-xs text-teal-800 dark:text-teal-400 space-y-2 mb-3">
                <div className="font-bold text-sm">Absolute Return (%) = [ ( Current Value - Initial Investment ) / Initial Investment ] × 100</div>
                <div className="text-[var(--text-muted)] font-sans text-[11px] space-y-0.5 pt-2">
                  <div><strong>Current Value</strong> = Final redemption price or current portfolio value</div>
                  <div><strong>Initial Investment</strong> = Original purchase cost or capital deployed</div>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-bold text-neutral-950 dark:text-neutral-50 mb-3">Absolute Return vs CAGR</h2>
              <div className="overflow-x-auto">
                <table className="financial-table text-xs w-full">
                  <thead>
                    <tr className="bg-neutral-50 dark:bg-[#121212] border-b border-[var(--border)]">
                      <th className="px-4 py-3 text-left">Parameter</th>
                      <th className="px-4 py-3 text-left">Absolute Return</th>
                      <th className="px-4 py-3 text-left">CAGR</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[var(--border)]">
                    <tr>
                      <td className="px-4 py-2.5 font-bold">Time Dimension</td>
                      <td className="px-4 py-2.5 text-amber-600 dark:text-amber-400">Ignores holding period</td>
                      <td className="px-4 py-2.5 text-teal-700 dark:text-teal-400 font-semibold">Standardized per year</td>
                    </tr>
                    <tr>
                      <td className="px-4 py-2.5 font-bold">Best Use Case</td>
                      <td className="px-4 py-2.5">Short-term trades (&lt; 1 Year)</td>
                      <td className="px-4 py-2.5 text-teal-700 dark:text-teal-400 font-semibold">Long-term investments (&gt; 1 Year)</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>

            {/* FAQ Accordion Section */}
            <div className="border-t border-[var(--border)] pt-8">
              <h2 className="text-xl font-bold text-neutral-950 dark:text-neutral-50 mb-6">Frequently Asked Questions</h2>
              <div className="space-y-3">
                {pageFaqItems.map((faq, idx) => (
                  <div key={idx} className="border border-[var(--border)] rounded-xl overflow-hidden">
                    <button
                      onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                      className="w-full px-5 py-3.5 flex items-center justify-between text-left text-sm font-semibold text-neutral-900 dark:text-white bg-white dark:bg-[#0a0a0a] hover:bg-neutral-50 dark:hover:bg-[#121212]/50 transition-colors focus:outline-none"
                      aria-expanded={openFaq === idx}
                    >
                      <span>{faq.question}</span>
                      {openFaq === idx ? <ChevronUp className="h-4 w-4 shrink-0 ml-3" /> : <ChevronDown className="h-4 w-4 shrink-0 ml-3" />}
                    </button>
                    {openFaq === idx && (
                      <div className="px-5 pb-4 text-xs text-[var(--text-secondary)] leading-relaxed bg-neutral-50/50 dark:bg-[#0a0a0a]">
                        {faq.answer}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Right Column: Sticky Related Calculators Sidebar */}
          <div className="lg:col-span-4 lg:sticky lg:top-20">
            <RelatedCalculators currentRoute="/calculators/absolute-return-calculator" />
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
