export interface RelatedCalculatorItem {
  name: string;
  href: string;
}

export const CALCULATOR_NAMES: Record<string, string> = {
  "/calculators/sip-calculator": "SIP Calculator",
  "/calculators/goal-sip-calculator": "Goal SIP Calculator",
  "/calculators/step-up-sip-calculator": "Step-Up SIP Calculator",
  "/calculators/swp-calculator": "SWP Calculator",
  "/calculators/stp-calculator": "STP Calculator",
  "/calculators/fd-calculator": "FD Calculator",
  "/calculators/rd-calculator": "RD Calculator",
  "/calculators/bond-calculator": "Bond Calculator",
  "/calculators/emi-calculator": "EMI Calculator",
  "/calculators/loan-amortization-calculator": "Loan Amortization Calculator",
  "/calculators/loan-prepayment-calculator": "Loan Prepayment Calculator",
  "/calculators/cagr-calculator": "CAGR Calculator",
  "/calculators/absolute-return-calculator": "Absolute Return Calculator",
  "/calculators/irr-calculator": "IRR Calculator",
  "/calculators/xirr-calculator": "XIRR Calculator",
  "/calculators/time-weighted-return-calculator": "Time-Weighted Return Calculator",
  "/calculators/inflation-calculator": "Inflation Calculator",
  "/calculators/retirement-calculator": "Retirement Calculator",
  "/calculators/emergency-fund-calculator": "Emergency Fund Calculator",
  "/calculators/compound-interest-calculator": "Compound Interest Calculator",
  "/calculators/future-value-calculator": "Future Value Calculator",
  "/calculators/present-value-calculator": "Present Value Calculator",
  "/calculators/dcf-calculator": "DCF Valuation Calculator",
  "/calculators/reverse-dcf-calculator": "Reverse DCF Calculator",
  "/calculators/pe-valuation-calculator": "P/E Valuation Calculator",
  "/calculators/ev-ebitda-calculator": "EV/EBITDA Calculator",
  "/calculators/ddm-calculator": "Dividend Discount Model (DDM) Calculator",
};

export const RELATED_CALCULATORS_MAP: Record<string, string[]> = {
  "/calculators/sip-calculator": [
    "/calculators/goal-sip-calculator",
    "/calculators/step-up-sip-calculator",
    "/calculators/swp-calculator",
    "/calculators/stp-calculator",
    "/calculators/cagr-calculator",
  ],
  "/calculators/goal-sip-calculator": [
    "/calculators/sip-calculator",
    "/calculators/step-up-sip-calculator",
    "/calculators/retirement-calculator",
    "/calculators/future-value-calculator",
    "/calculators/compound-interest-calculator",
  ],
  "/calculators/step-up-sip-calculator": [
    "/calculators/sip-calculator",
    "/calculators/goal-sip-calculator",
    "/calculators/cagr-calculator",
    "/calculators/future-value-calculator",
    "/calculators/retirement-calculator",
  ],
  "/calculators/swp-calculator": [
    "/calculators/sip-calculator",
    "/calculators/goal-sip-calculator",
    "/calculators/stp-calculator",
    "/calculators/retirement-calculator",
    "/calculators/cagr-calculator",
  ],
  "/calculators/stp-calculator": [
    "/calculators/sip-calculator",
    "/calculators/swp-calculator",
    "/calculators/cagr-calculator",
    "/calculators/xirr-calculator",
    "/calculators/absolute-return-calculator",
  ],
  "/calculators/fd-calculator": [
    "/calculators/rd-calculator",
    "/calculators/bond-calculator",
    "/calculators/compound-interest-calculator",
    "/calculators/future-value-calculator",
    "/calculators/inflation-calculator",
  ],
  "/calculators/rd-calculator": [
    "/calculators/fd-calculator",
    "/calculators/bond-calculator",
    "/calculators/compound-interest-calculator",
    "/calculators/future-value-calculator",
    "/calculators/inflation-calculator",
  ],
  "/calculators/bond-calculator": [
    "/calculators/fd-calculator",
    "/calculators/rd-calculator",
    "/calculators/dcf-calculator",
    "/calculators/pe-valuation-calculator",
    "/calculators/inflation-calculator",
  ],
  "/calculators/emi-calculator": [
    "/calculators/loan-amortization-calculator",
    "/calculators/loan-prepayment-calculator",
    "/calculators/compound-interest-calculator",
    "/calculators/present-value-calculator",
    "/calculators/future-value-calculator",
  ],
  "/calculators/loan-amortization-calculator": [
    "/calculators/emi-calculator",
    "/calculators/loan-prepayment-calculator",
    "/calculators/present-value-calculator",
    "/calculators/future-value-calculator",
    "/calculators/compound-interest-calculator",
  ],
  "/calculators/loan-prepayment-calculator": [
    "/calculators/emi-calculator",
    "/calculators/loan-amortization-calculator",
    "/calculators/future-value-calculator",
    "/calculators/present-value-calculator",
    "/calculators/compound-interest-calculator",
  ],
  "/calculators/cagr-calculator": [
    "/calculators/absolute-return-calculator",
    "/calculators/irr-calculator",
    "/calculators/xirr-calculator",
    "/calculators/sip-calculator",
    "/calculators/compound-interest-calculator",
  ],
  "/calculators/absolute-return-calculator": [
    "/calculators/cagr-calculator",
    "/calculators/irr-calculator",
    "/calculators/xirr-calculator",
    "/calculators/time-weighted-return-calculator",
    "/calculators/sip-calculator",
  ],
  "/calculators/irr-calculator": [
    "/calculators/xirr-calculator",
    "/calculators/cagr-calculator",
    "/calculators/absolute-return-calculator",
    "/calculators/time-weighted-return-calculator",
    "/calculators/dcf-calculator",
  ],
  "/calculators/xirr-calculator": [
    "/calculators/irr-calculator",
    "/calculators/cagr-calculator",
    "/calculators/absolute-return-calculator",
    "/calculators/time-weighted-return-calculator",
    "/calculators/sip-calculator",
  ],
  "/calculators/time-weighted-return-calculator": [
    "/calculators/xirr-calculator",
    "/calculators/irr-calculator",
    "/calculators/cagr-calculator",
    "/calculators/absolute-return-calculator",
    "/calculators/sip-calculator",
  ],
  "/calculators/inflation-calculator": [
    "/calculators/retirement-calculator",
    "/calculators/future-value-calculator",
    "/calculators/present-value-calculator",
    "/calculators/compound-interest-calculator",
    "/calculators/fd-calculator",
  ],
  "/calculators/retirement-calculator": [
    "/calculators/sip-calculator",
    "/calculators/goal-sip-calculator",
    "/calculators/inflation-calculator",
    "/calculators/compound-interest-calculator",
    "/calculators/future-value-calculator",
  ],
  "/calculators/emergency-fund-calculator": [
    "/calculators/sip-calculator",
    "/calculators/goal-sip-calculator",
    "/calculators/inflation-calculator",
    "/calculators/compound-interest-calculator",
    "/calculators/future-value-calculator",
  ],
  "/calculators/compound-interest-calculator": [
    "/calculators/future-value-calculator",
    "/calculators/present-value-calculator",
    "/calculators/cagr-calculator",
    "/calculators/sip-calculator",
    "/calculators/inflation-calculator",
  ],
  "/calculators/future-value-calculator": [
    "/calculators/present-value-calculator",
    "/calculators/compound-interest-calculator",
    "/calculators/cagr-calculator",
    "/calculators/inflation-calculator",
    "/calculators/retirement-calculator",
  ],
  "/calculators/present-value-calculator": [
    "/calculators/future-value-calculator",
    "/calculators/compound-interest-calculator",
    "/calculators/dcf-calculator",
    "/calculators/emi-calculator",
    "/calculators/inflation-calculator",
  ],
  "/calculators/dcf-calculator": [
    "/calculators/reverse-dcf-calculator",
    "/calculators/pe-valuation-calculator",
    "/calculators/ev-ebitda-calculator",
    "/calculators/ddm-calculator",
    "/calculators/irr-calculator",
  ],
  "/calculators/reverse-dcf-calculator": [
    "/calculators/dcf-calculator",
    "/calculators/pe-valuation-calculator",
    "/calculators/ev-ebitda-calculator",
    "/calculators/ddm-calculator",
    "/calculators/cagr-calculator",
  ],
  "/calculators/pe-valuation-calculator": [
    "/calculators/dcf-calculator",
    "/calculators/reverse-dcf-calculator",
    "/calculators/ev-ebitda-calculator",
    "/calculators/ddm-calculator",
    "/calculators/cagr-calculator",
  ],
  "/calculators/ev-ebitda-calculator": [
    "/calculators/dcf-calculator",
    "/calculators/reverse-dcf-calculator",
    "/calculators/pe-valuation-calculator",
    "/calculators/ddm-calculator",
    "/calculators/cagr-calculator",
  ],
  "/calculators/ddm-calculator": [
    "/calculators/dcf-calculator",
    "/calculators/pe-valuation-calculator",
    "/calculators/ev-ebitda-calculator",
    "/calculators/reverse-dcf-calculator",
    "/calculators/cagr-calculator",
  ],
};

export function getRelatedCalculators(route: string): RelatedCalculatorItem[] {
  const routes = RELATED_CALCULATORS_MAP[route] || [];
  return routes.map((r) => ({
    name: CALCULATOR_NAMES[r] || "Financial Calculator",
    href: r,
  }));
}
